### ISSUE TITLE
Question on dependencies/pods

### ISSUE THREAD

**Issue by precipice** [justinweiss/dragongoclient#19]
Some of the included pods—particularly InnerBand and MKNetworkKit—have a bunch of warnings. It looks like MKNetworkKit has just abandoned Cocoapods altogether (pod version = 0.87; current version = 2.0; see also http://blog.mugunthkumar.com/articles/the-problem-with-cocoapods/), and InnerBand is not in active development (see for instance https://github.com/ZaBlanc/InnerBand/pull/13 open for ~3 years). 

I suspect I can resolve these one of a few ways:

1. Provide local podspecs if the developers don't have them available otherwise (and submit pull requests to them).
1. Vendor any library where pods are not in active development.
1. Tear out cocoapods altogether.
1. Replace libraries out of current development with other libraries.

The last of those is a little daunting as a first step, but I'm up for any of those options (or some combination of them). What would you prefer?

If there's a better option I'm not considering, let me know.

**Comment by justinweiss** [comment]
I would love to replace MKNetworkKit with the built-in NSURLConnection stuff. It opens up a lot of possibilities with silent push notifications and background downloading that should make the experience of opening the app a lot more seamless. 

Same thing with InnerBand -- I think I just grabbed it because it was convenient, but I believe a lot of that convenience is built into iOS at this point. (Original development of the DGS app started in iOS 4!) If there's a good way to do this stuff natively, I'd prefer that. I'm totally willing to help, answer questions, and make decisions.

**Comment by precipice** [comment]
@justinweiss: awesome. I'll take that option. It looks like InnerBand, which has by far the most warnings, and is very lightly used (I only see IBAlertView in use, though that prefix makes searching a little annoying!). I'll tear that out first.

Thanks much!
